# """
# Docker Compose конфігурація для всього проєкту.
#
# Тут описані три сервіси:
# база даних PostgreSQL, Python-застосунок і nginx як reverse proxy.
# Також визначений окремий volume для збереження даних бази.
# """
services:
  # """
  # Сервіс бази даних.
  #
  # Він запускає PostgreSQL, читає змінні з `.env`,
  # зберігає дані в окремому volume
  # і виконує init.sql під час ініціалізації нової бази.
  # """
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # """
  # Сервіс Python-застосунку.
  #
  # Він збирається з локального Dockerfile,
  # використовує змінні середовища з `.env`,
  # монтує папку із зображеннями
  # і стартує тільки після готовності бази даних.
  # """
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./images:/images
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  # """
  # Сервіс nginx.
  #
  # Він працює як вхідна точка для HTTP-запитів:
  # напряму віддає статичні файли та зображення
  # і проксіює інші запити на Python backend.
  # """
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
      - ./src/static:/app/src/static:ro
    depends_on:
      - app

# """
# Іменований volume для збереження даних PostgreSQL
# між перезапусками контейнерів.
# """
volumes:
  db_data:
